<?php
require "../vendor/autoload.php";             //class autoloading @generated by Composer

use League\Plates\Engine;

$templates = new Engine( '../views');

echo $templates->render("../views/home", [
	"pageTitle" => "Curso Aplicaciones Profesionales en PHP",
	"title" => "Portada de mi sitio web",
	"creator" => "DesarrolloWeb.com"
]);