<?php
require '../vendor/autoload.php';          //class autoloading @generated by Composer

use Carbon\Carbon;
use Controller\Dates;
use League\Plates\Engine;

$date = Carbon::now();
echo $date->format("d M Y"). "<br>";

Carbon::setLocale("es");
$today    = Carbon::now();
$tomorrow = $today->addDays(1);
echo $tomorrow->isoFormat("dddd DD [de] MMMM"). "<br>";

// include "./src/Controller/Dates.php";    //commented thanks to composer dump-autoload
echo Controller\Dates::longDate(Controller\Dates::today()). "<br>";
echo Dates::longDate(Dates::tomorrow());

$templates = new Engine("../views");
echo $templates->render('template-test', [
    'subtitle' => 'Subtitle sended to a Plates template.'
]);