<?php
require '../vendor/autoload.php';          //class autoloading @generated by Composer

use League\Plates\Engine;

$templates = new Engine("../views");
// echo $templates->render('../views/layouts/template', [
//   'subtitle' => 'Greetings page 1...'
// ]);
echo $templates->render('../views/profile', [
    'name' => 'Juan'
]);